server:
  port: ${PORT:4110}

spring:
  application:
    name: apartment-service
  datasource:
    url: jdbc:postgresql://${WORK_PERMISSION_DB_IP}:${WORK_PERMISSION_DB_PORT}/apartmentservicedatabase
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration: DEBUG

# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  override-with-generic-response: false

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true